
//////Try...Catch//////////////////////////////////////////////////////////////////////////////////

public class Main 
{
  public static void main(String[ ] args) 
  {
    try 
    {
      int[] myNumbers = {1, 2, 3};
      System.out.println(myNumbers[10]);
    } 
    catch (Exception e) 
    {
      System.out.println("Something went wrong.");
    }
  }
}


///////finally statement lets you execute code, after try...catch//////////////////////////////////
public class Main 
{
  public static void main(String[] args) 
  {
    try 
    {
      int[] myNumbers = {1, 2, 3};
      System.out.println(myNumbers[10]);
    } 
    catch (Exception e) 
    {
      System.out.println("Something went wrong.");
    } 
    finally 
    {
      System.out.println("The 'try catch' is finished.");
    }
  }
}


/////////throw keyword//////////////////////////////////
The throw statement is used together with an exception type. There are many exception types available in Java: 
1. ArithmeticException
2. FileNotFoundException
3. ArrayIndexOutOfBoundsException
4. SecurityException

public class Main {
  static void checkAge(int age) {
    if (age < 18) {
      throw new ArithmeticException("Access denied - You must be at least 18 years old.");
    }
    else {
      System.out.println("Access granted - You are old enough!");
    }
  }

  public static void main(String[] args) {
    checkAge(15); // Set age to 15 (which is below 18...)
  }
}


